version: '3.5'
services:
  nginx:
    build: ./nginx/
    container_name: nginx-container
    ports:
      - 80:80
    volumes:
      - ./www/html/:/var/www/html/
    networks:
      - wordpress

  php:
    build: ./php/
    container_name: php-container
    expose:
      - 9000
    volumes:
      - ./www/html:/var/www/html
    networks:
      - wordpress
  
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"
    networks:
      - wordpress

networks:
  wordpress:
    name: wordpress
